// Completes men's matches 1-4 so the points table & stats populate, then clean.
import { readFileSync } from 'node:fs';
import { deriveMatchState, computeNetRunEffect, computeStrikeChanged, shouldReBowl } from '../src/lib/engine';
import { MENS_MATCHES, mensPairs, MENS_PLAYERS } from '../src/lib/mensData';
const env=readFileSync('/Users/viratgandhi/cricket-scorer/.env.local','utf8');
const g=(k)=>env.match(new RegExp(`^${k}=(.*)$`,'m'))?.[1]?.trim()??'';
const BASE=g('VITE_SUPABASE_URL').replace(/\/$/,'')+'/rest/v1';
const KEY=g('VITE_SUPABASE_ANON_KEY'); const H={apikey:KEY,Authorization:`Bearer ${KEY}`,'Content-Type':'application/json'};
const SENT='00000000-0000-0000-00f8-'; let idc=Math.floor(Math.random()*0xffffff); const nid=()=>SENT+(idc++).toString(16).padStart(12,'0'); const posted=[];
let seed=3; const rnd=()=>{seed=(seed*1103515245+12345)&0x7fffffff;return seed/0x7fffffff;};
const S=MENS_MATCHES[0].match.settings; const TOTAL=S.num_pairs*S.overs_per_pair*S.balls_per_over;
async function inn(inningsId,pairs,bowlers,aggr){const dels=[];let n=0;while(true){const d0=deriveMatchState(dels,pairs,S);if(d0.is_complete)break;const nb=d0.next_ball;const bw=bowlers[Math.floor(d0.current_absolute_over)%bowlers.length];const x=rnd();const wide=!nb.is_last_ball_of_pair_set&&x<0.05;const wkt=!wide&&x>0.95;const y=rnd()*aggr;const r=wide||wkt?0:y>0.9?6:y>0.78?4:y>0.55?2:y>0.28?1:0;const isRB=shouldReBowl(wide?'wide':'none',nb.is_last_ball_of_pair_set,S);const lb=!isRB;const eo=lb&&nb.ball_in_over===S.balls_per_over-1;const ev=wide?(isRB?1:S.wide_value):0;const w=isRB?false:wkt;n++;const d={id:nid(),innings_id:inningsId,pair_id:d0.current_pair.id,over_number:nb.over_number,ball_in_over:nb.ball_in_over,sequence_number:n,is_deleted:false,striker_id:d0.striker_id,non_striker_id:d0.non_striker_id,bowler_id:bw.id,runs_off_bat:r,extra_type:wide?'wide':'none',extra_value:ev,is_wicket:w,wicket_type:w?'caught':undefined,dismissed_player_id:w?d0.striker_id:undefined,fielder_id:w?bw.id:undefined,net_run_effect:computeNetRunEffect(r,ev,w,S),legal_ball:lb,strike_changed:computeStrikeChanged(r,w,eo,false),created_at:new Date().toISOString()};const res=await fetch(`${BASE}/deliveries`,{method:'POST',headers:H,body:JSON.stringify(d)});if(!res.ok)throw new Error(await res.text());posted.push(d.id);dels.push(d);}return deriveMatchState(dels,pairs,S).total;}
async function complete(m,ag1,ag2){await fetch(`${BASE}/matches?id=eq.${m.match.id}`,{method:'PATCH',headers:H,body:JSON.stringify({toss_winner_id:m.match.home_team_id,toss_decision:'bat'})});const a=await inn(m.innings1_id,mensPairs(m.match.home_team_id,m.match.id),MENS_PLAYERS.filter(p=>p.team_id===m.match.away_team_id),ag1);const b=await inn(m.innings2_id,mensPairs(m.match.away_team_id,m.match.id),MENS_PLAYERS.filter(p=>p.team_id===m.match.home_team_id),ag2);return[a,b];}
async function clean(){for(const r of MENS_MATCHES){const rows=await(await fetch(`${BASE}/deliveries?innings_id=in.(${r.innings1_id},${r.innings2_id})&select=id`,{headers:H})).json();const s=rows.filter(x=>x.id.startsWith(SENT)).map(x=>x.id);for(let i=0;i<s.length;i+=50)await fetch(`${BASE}/deliveries?id=in.(${s.slice(i,i+50).join(',')})`,{method:'PATCH',headers:H,body:JSON.stringify({is_deleted:true})});await fetch(`${BASE}/matches?id=eq.${r.match.id}`,{method:'PATCH',headers:H,body:JSON.stringify({toss_winner_id:null,toss_decision:null})});}console.log('cleaned');}
(async()=>{if(process.argv[2]==='clean'){await clean();return;}const r1=await complete(MENS_MATCHES[0],1.1,0.9);const r2=await complete(MENS_MATCHES[1],1.0,1.15);const r3=await complete(MENS_MATCHES[2],0.9,1.1);const r4=await complete(MENS_MATCHES[3],1.2,0.85);console.log('M1',r1,'M2',r2,'M3',r3,'M4',r4);console.log('DONE');})().catch(e=>{console.error(e.message);process.exit(1);});
