import puppeteer from 'puppeteer-core';
const CHROME='/Applications/Google Chrome.app/Contents/MacOS/Google Chrome';
const b=await puppeteer.launch({executablePath:CHROME,headless:'new',args:['--no-sandbox','--hide-scrollbars']});
const p=await b.newPage(); await p.setViewport({width:390,height:2200,deviceScaleFactor:2,isMobile:true});
await p.goto('https://aicc-aia-cricket.com/womens',{waitUntil:'networkidle2'}); await new Promise(r=>setTimeout(r,2000));
await p.evaluate(()=>{for(const el of document.querySelectorAll('button')){if(el.textContent.trim()==='Fixtures'){el.click();return;}}});
await new Promise(r=>setTimeout(r,2000));
const txt=await p.evaluate(()=>{const t=document.body.innerText;const i=t.indexOf('Round 2');return i<0?t.slice(0,400):t.slice(i,i+500).replace(/\n+/g,' | ');});
console.log('ROUND 2 FIXTURES:', txt);
await b.close();
