// Completes women's Round 1 (matches 1-6) so group tables populate, then clean.
import { readFileSync } from 'node:fs';
import { deriveMatchState, computeNetRunEffect, computeStrikeChanged, shouldReBowl } from '../src/lib/engine';
import { ALL_MATCHES, getPairsForTeam } from '../src/lib/matchData';
import { PLAYERS } from '../src/lib/seedData';
const env=readFileSync('/Users/viratgandhi/cricket-scorer/.env.local','utf8');
const g=(k)=>env.match(new RegExp(`^${k}=(.*)$`,'m'))?.[1]?.trim()??'';
const BASE=g('VITE_SUPABASE_URL').replace(/\/$/,'')+'/rest/v1';
const KEY=g('VITE_SUPABASE_ANON_KEY'); const H={apikey:KEY,Authorization:`Bearer ${KEY}`,'Content-Type':'application/json'};
const SENT='00000000-0000-0000-00f7-'; let idc=Math.floor(Math.random()*0xffffff); const nid=()=>SENT+(idc++).toString(16).padStart(12,'0');
let seed=5; const rnd=()=>{seed=(seed*1103515245+12345)&0x7fffffff;return seed/0x7fffffff;};
const S=ALL_MATCHES[0].match.settings;
async function inn(inningsId,pairs,bowlers,aggr){const dels=[];let n=0;while(true){const d0=deriveMatchState(dels,pairs,S);if(d0.is_complete)break;const nb=d0.next_ball;const bw=bowlers[Math.floor(d0.current_absolute_over)%bowlers.length];const x=rnd();const wide=!nb.is_last_ball_of_pair_set&&x<0.05;const wkt=!wide&&x>0.95;const y=rnd()*aggr;const r=wide||wkt?0:y>0.9?6:y>0.78?4:y>0.55?2:y>0.28?1:0;const isRB=shouldReBowl(wide?'wide':'none',nb.is_last_ball_of_pair_set,S);const lb=!isRB;const eo=lb&&nb.ball_in_over===S.balls_per_over-1;const ev=wide?(isRB?1:S.wide_value):0;const w=isRB?false:wkt;n++;const d={id:nid(),innings_id:inningsId,pair_id:d0.current_pair.id,over_number:nb.over_number,ball_in_over:nb.ball_in_over,sequence_number:n,is_deleted:false,striker_id:d0.striker_id,non_striker_id:d0.non_striker_id,bowler_id:bw.id,runs_off_bat:r,extra_type:wide?'wide':'none',extra_value:ev,is_wicket:w,wicket_type:w?'caught':undefined,dismissed_player_id:w?d0.striker_id:undefined,fielder_id:w?bw.id:undefined,net_run_effect:computeNetRunEffect(r,ev,w,S),legal_ball:lb,strike_changed:computeStrikeChanged(r,w,eo,false),created_at:new Date().toISOString()};const res=await fetch(`${BASE}/deliveries`,{method:'POST',headers:H,body:JSON.stringify(d)});if(!res.ok)throw new Error(await res.text());dels.push(d);}return deriveMatchState(dels,pairs,S).total;}
async function complete(m,a1,a2){await fetch(`${BASE}/matches?id=eq.${m.match.id}`,{method:'PATCH',headers:H,body:JSON.stringify({toss_winner_id:m.match.home_team_id,toss_decision:'bat'})});const a=await inn(m.innings1_id,getPairsForTeam(m.match.home_team_id,m.match.id),PLAYERS.filter(p=>p.team_id===m.match.away_team_id),a1);const b=await inn(m.innings2_id,getPairsForTeam(m.match.away_team_id,m.match.id),PLAYERS.filter(p=>p.team_id===m.match.home_team_id),a2);return[a,b];}
async function clean(){for(const r of ALL_MATCHES){const rows=await(await fetch(`${BASE}/deliveries?innings_id=in.(${r.innings1_id},${r.innings2_id})&select=id`,{headers:H})).json();const s=rows.filter(x=>x.id.startsWith(SENT)).map(x=>x.id);for(let i=0;i<s.length;i+=50)await fetch(`${BASE}/deliveries?id=in.(${s.slice(i,i+50).join(',')})`,{method:'PATCH',headers:H,body:JSON.stringify({is_deleted:true})});await fetch(`${BASE}/matches?id=eq.${r.match.id}`,{method:'PATCH',headers:H,body:JSON.stringify({toss_winner_id:null,toss_decision:null})});}console.log('cleaned');}
(async()=>{if(process.argv[2]==='clean'){await clean();return;}for(let i=0;i<6;i++){await complete(ALL_MATCHES[i],1+rnd()*0.3,1+rnd()*0.3);}console.log('DONE 6 matches');})().catch(e=>{console.error(e.message);process.exit(1);});
